# This file contains the configuration for the home (default path) page.

# Everything in this file is listen in chronological order to how they appear on the page.
# Both HTML and Markdown are supported in most values.


# The large text at the top of the page.
title: "Calendar"
# The smaller text below the title.
subtitle: ""

# Google Calendar embed link
embed: "https://calendar.google.com/calendar/u/0/r/month/2025/10/25"
